name: 'push-ghcr'

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "WillFP"
          password: ${{ secrets.ACCESS_TOKEN }}
          repository: auxilor/lrcdb
          tags: latest